create extension if not exists pgcrypto;

do $$
begin
  create type public.clinic_role as enum ('clinic_admin', 'vet', 'assistant');
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create type public.clinic_status as enum ('trial', 'active', 'past_due', 'canceled');
exception
  when duplicate_object then null;
end
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.clients (
  id bigint primary key generated by default as identity,
  clinic_id uuid,
  first_name text,
  last_name text,
  birthdate text,
  address text,
  city text,
  phone text,
  secondary_phone text,
  email text,
  personal_id_number text,
  id_card_number text,
  obs text
);

create table if not exists public.pets (
  id bigint primary key generated by default as identity,
  clinic_id uuid,
  client_id bigint,
  nickname text,
  species text,
  breed text,
  crossbreed text,
  mix_with text,
  color text,
  distinctive_marks text,
  birthday text,
  gender text,
  chip_number text,
  rabic_tag_number text,
  microchip_location text,
  insurance_number text,
  passport text,
  pet_description text,
  weight text,
  allergies text,
  blood_type text,
  hormonal_status text,
  obs text
);

create table if not exists public.vets (
  id bigint primary key generated by default as identity,
  clinic_id uuid,
  email text,
  first_name text,
  last_name text,
  title text,
  phone text,
  status text,
  license_number text,
  created_at text,
  updated_at text
);

create table if not exists public.appointments (
  id bigint primary key generated by default as identity,
  clinic_id uuid,
  patient_id bigint,
  vet_id bigint,
  service text,
  observations text,
  date text,
  duration text,
  reason text,
  notification_message text,
  user_note text
);

create table if not exists public.records (
  id bigint primary key generated by default as identity,
  clinic_id uuid,
  date text,
  pet_id bigint,
  pet text,
  vet text,
  service text,
  diagnosis text,
  diagnosis_description text,
  presumptive_diagnosis text,
  treatment_description text,
  recommendations text,
  comments text
);

create table if not exists public.prescriptions (
  id bigint primary key generated by default as identity,
  clinic_id uuid,
  record_id bigint,
  vet_id bigint,
  pet_id bigint,
  product_name text,
  quantity text,
  unit text,
  label text,
  recommendations text,
  prescribed_at text,
  expires_at text,
  status text,
  internal_notes text,
  created_at text,
  updated_at text
);

create table if not exists public.reminders (
  id bigint primary key generated by default as identity,
  clinic_id uuid,
  pet_id bigint,
  protocol_name text,
  name text,
  administration_date text,
  due_date text,
  sms_sent_at timestamptz,
  sms_sent_2d_at timestamptz
);

create table if not exists public.sales (
  id bigint primary key generated by default as identity,
  clinic_id uuid,
  vet_id bigint,
  customer_id bigint,
  invoice_id text,
  subtotal text,
  total text,
  tax_amount text,
  amount_paid text,
  payment_type text,
  status text,
  payment_date text,
  created_at text,
  updated_at text
);

create table if not exists public.clinics (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  legal_name text not null,
  cui_cif text not null,
  trade_register_number text not null,
  is_vat_payer boolean not null default false,
  billing_address text not null,
  county text not null,
  city text not null,
  country_code text not null default 'RO',
  contact_email text not null,
  contact_phone text not null,
  status public.clinic_status not null default 'trial',
  currency text not null default 'EUR',
  trial_started_at timestamptz not null default timezone('utc', now()),
  trial_end timestamptz not null default timezone('utc', now()) + interval '30 days',
  grace_end timestamptz not null default timezone('utc', now()) + interval '32 days',
  owner_user_id uuid references auth.users(id) on delete set null,
  terms_accepted_at timestamptz not null default timezone('utc', now()),
  privacy_accepted_at timestamptz not null default timezone('utc', now()),
  dpa_accepted_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists clinics_cui_cif_key on public.clinics (cui_cif);
create index if not exists clinics_owner_user_id_idx on public.clinics (owner_user_id);
create index if not exists clinics_status_idx on public.clinics (status);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  first_name text,
  last_name text,
  full_name text,
  active_clinic_id uuid references public.clinics(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists profiles_active_clinic_id_idx on public.profiles (active_clinic_id);

create table if not exists public.user_clinics (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  clinic_id uuid not null references public.clinics(id) on delete cascade,
  role public.clinic_role not null default 'assistant',
  is_owner boolean not null default false,
  invited_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, clinic_id)
);

create index if not exists user_clinics_user_id_idx on public.user_clinics (user_id);
create index if not exists user_clinics_clinic_id_idx on public.user_clinics (clinic_id);

create table if not exists public.clinic_invites (
  id uuid primary key default gen_random_uuid(),
  clinic_id uuid not null references public.clinics(id) on delete cascade,
  email text not null,
  role public.clinic_role not null default 'assistant',
  invited_by uuid references auth.users(id) on delete set null,
  token text not null unique,
  expires_at timestamptz not null default timezone('utc', now()) + interval '7 days',
  accepted_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists clinic_invites_clinic_id_idx on public.clinic_invites (clinic_id);
create index if not exists clinic_invites_email_idx on public.clinic_invites (email);

create table if not exists public.clinic_settings (
  clinic_id uuid primary key references public.clinics(id) on delete cascade,
  timezone text not null default 'Europe/Bucharest',
  locale text not null default 'ro-RO',
  trial_user_limit integer not null default 2,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.billing_events (
  id uuid primary key default gen_random_uuid(),
  clinic_id uuid not null references public.clinics(id) on delete cascade,
  provider text not null default 'euplatesc',
  external_id text,
  status text not null,
  amount_cents integer,
  currency text not null default 'EUR',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists billing_events_clinic_id_idx on public.billing_events (clinic_id);
create unique index if not exists billing_events_provider_external_id_idx
  on public.billing_events (provider, external_id)
  where external_id is not null;

create table if not exists public.audit_logs (
  id bigint generated always as identity primary key,
  clinic_id uuid not null references public.clinics(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  table_name text not null,
  action text not null,
  record_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists audit_logs_clinic_id_idx on public.audit_logs (clinic_id);

create table if not exists public.auth_mfa_factors (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  secret text not null,
  verified boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists auth_mfa_factors_email_idx on public.auth_mfa_factors (email);

create table if not exists public.auth_log (
  id bigint generated always as identity primary key,
  ip text,
  username text,
  event text not null,
  user_agent text,
  created_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'clinics_set_updated_at'
  ) then
    create trigger clinics_set_updated_at
      before update on public.clinics
      for each row
      execute function public.set_updated_at();
  end if;

  if not exists (
    select 1
    from pg_trigger
    where tgname = 'profiles_set_updated_at'
  ) then
    create trigger profiles_set_updated_at
      before update on public.profiles
      for each row
      execute function public.set_updated_at();
  end if;

  if not exists (
    select 1
    from pg_trigger
    where tgname = 'clinic_settings_set_updated_at'
  ) then
    create trigger clinic_settings_set_updated_at
      before update on public.clinic_settings
      for each row
      execute function public.set_updated_at();
  end if;

  if not exists (
    select 1
    from pg_trigger
    where tgname = 'auth_mfa_factors_set_updated_at'
  ) then
    create trigger auth_mfa_factors_set_updated_at
      before update on public.auth_mfa_factors
      for each row
      execute function public.set_updated_at();
  end if;
end
$$;

insert into public.clinics (
  id,
  name,
  legal_name,
  cui_cif,
  trade_register_number,
  is_vat_payer,
  billing_address,
  county,
  city,
  country_code,
  contact_email,
  contact_phone,
  status,
  currency,
  trial_started_at,
  trial_end,
  grace_end,
  terms_accepted_at,
  privacy_accepted_at,
  dpa_accepted_at
)
values (
  '00000000-0000-0000-0000-000000000001',
  'Legacy Clinic',
  'Legacy Clinic',
  'LEGACY-CANISVET',
  'J00/0000/2026',
  false,
  'Legacy address',
  'Arad',
  'Arad',
  'RO',
  'legacy@secforit.ro',
  '0000000000',
  'active',
  'EUR',
  timezone('utc', now()),
  timezone('utc', now()) + interval '365 days',
  timezone('utc', now()) + interval '367 days',
  timezone('utc', now()),
  timezone('utc', now()),
  timezone('utc', now())
)
on conflict (id) do nothing;

insert into public.clinic_settings (clinic_id, timezone, locale, trial_user_limit)
values ('00000000-0000-0000-0000-000000000001', 'Europe/Bucharest', 'ro-RO', 2)
on conflict (clinic_id) do nothing;

alter table if exists public.clients add column if not exists clinic_id uuid references public.clinics(id) on delete restrict;
alter table if exists public.pets add column if not exists clinic_id uuid references public.clinics(id) on delete restrict;
alter table if exists public.vets add column if not exists clinic_id uuid references public.clinics(id) on delete restrict;
alter table if exists public.appointments add column if not exists clinic_id uuid references public.clinics(id) on delete restrict;
alter table if exists public.records add column if not exists clinic_id uuid references public.clinics(id) on delete restrict;
alter table if exists public.prescriptions add column if not exists clinic_id uuid references public.clinics(id) on delete restrict;
alter table if exists public.reminders add column if not exists clinic_id uuid references public.clinics(id) on delete restrict;
alter table if exists public.sales add column if not exists clinic_id uuid references public.clinics(id) on delete restrict;
alter table if exists public.reminders add column if not exists sms_sent_at timestamptz;
alter table if exists public.reminders add column if not exists sms_sent_2d_at timestamptz;

update public.clients set clinic_id = '00000000-0000-0000-0000-000000000001' where clinic_id is null;
update public.pets set clinic_id = '00000000-0000-0000-0000-000000000001' where clinic_id is null;
update public.vets set clinic_id = '00000000-0000-0000-0000-000000000001' where clinic_id is null;
update public.appointments set clinic_id = '00000000-0000-0000-0000-000000000001' where clinic_id is null;
update public.records set clinic_id = '00000000-0000-0000-0000-000000000001' where clinic_id is null;
update public.prescriptions set clinic_id = '00000000-0000-0000-0000-000000000001' where clinic_id is null;
update public.reminders set clinic_id = '00000000-0000-0000-0000-000000000001' where clinic_id is null;
update public.sales set clinic_id = '00000000-0000-0000-0000-000000000001' where clinic_id is null;

alter table if exists public.clients alter column clinic_id set not null;
alter table if exists public.pets alter column clinic_id set not null;
alter table if exists public.vets alter column clinic_id set not null;
alter table if exists public.appointments alter column clinic_id set not null;
alter table if exists public.records alter column clinic_id set not null;
alter table if exists public.prescriptions alter column clinic_id set not null;
alter table if exists public.reminders alter column clinic_id set not null;
alter table if exists public.sales alter column clinic_id set not null;

create index if not exists clients_clinic_id_idx on public.clients (clinic_id);
create index if not exists pets_clinic_id_idx on public.pets (clinic_id);
create index if not exists vets_clinic_id_idx on public.vets (clinic_id);
create index if not exists appointments_clinic_id_idx on public.appointments (clinic_id);
create index if not exists records_clinic_id_idx on public.records (clinic_id);
create index if not exists prescriptions_clinic_id_idx on public.prescriptions (clinic_id);
create index if not exists reminders_clinic_id_idx on public.reminders (clinic_id);
create index if not exists sales_clinic_id_idx on public.sales (clinic_id);

create or replace function public.user_is_member(target_clinic uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.user_clinics uc
    where uc.user_id = auth.uid()
      and uc.clinic_id = target_clinic
  );
$$;

create or replace function public.user_is_clinic_admin(target_clinic uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.user_clinics uc
    where uc.user_id = auth.uid()
      and uc.clinic_id = target_clinic
      and uc.role = 'clinic_admin'
  );
$$;

create or replace function public.user_can_access_clinic(target_clinic uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.user_clinics uc
    join public.clinics c on c.id = uc.clinic_id
    where uc.user_id = auth.uid()
      and uc.clinic_id = target_clinic
      and (
        c.status in ('trial', 'active')
        or (
          c.status = 'past_due'
          and c.grace_end > timezone('utc', now())
        )
      )
  );
$$;

create or replace function public.clinic_trial_user_cap_available(target_clinic uuid)
returns boolean
language sql
stable
as $$
  select case
    when not exists (
      select 1
      from public.clinics c
      where c.id = target_clinic
        and c.status = 'trial'
    ) then true
    else (
      select
        (
          select count(*)
          from public.user_clinics uc
          where uc.clinic_id = target_clinic
        ) < coalesce(
          (
            select cs.trial_user_limit
            from public.clinic_settings cs
            where cs.clinic_id = target_clinic
          ),
          2
        )
    )
  end;
$$;

alter table public.clinics enable row level security;
alter table public.profiles enable row level security;
alter table public.user_clinics enable row level security;
alter table public.clinic_invites enable row level security;
alter table public.clinic_settings enable row level security;
alter table public.billing_events enable row level security;
alter table public.audit_logs enable row level security;
alter table public.auth_mfa_factors enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles
  for select
  using (auth.uid() = user_id);

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists clinics_select_member on public.clinics;
create policy clinics_select_member on public.clinics
  for select
  using (public.user_can_access_clinic(id));

drop policy if exists clinics_update_admin on public.clinics;
create policy clinics_update_admin on public.clinics
  for update
  using (public.user_is_clinic_admin(id))
  with check (public.user_is_clinic_admin(id));

drop policy if exists user_clinics_select_member on public.user_clinics;
create policy user_clinics_select_member on public.user_clinics
  for select
  using (auth.uid() = user_id or public.user_is_clinic_admin(clinic_id));

drop policy if exists user_clinics_insert_admin on public.user_clinics;
create policy user_clinics_insert_admin on public.user_clinics
  for insert
  with check (
    public.user_is_clinic_admin(clinic_id)
    and public.clinic_trial_user_cap_available(clinic_id)
  );

drop policy if exists user_clinics_update_admin on public.user_clinics;
create policy user_clinics_update_admin on public.user_clinics
  for update
  using (public.user_is_clinic_admin(clinic_id))
  with check (public.user_is_clinic_admin(clinic_id));

drop policy if exists user_clinics_delete_admin on public.user_clinics;
create policy user_clinics_delete_admin on public.user_clinics
  for delete
  using (public.user_is_clinic_admin(clinic_id));

drop policy if exists clinic_invites_select_admin on public.clinic_invites;
create policy clinic_invites_select_admin on public.clinic_invites
  for select
  using (public.user_is_clinic_admin(clinic_id));

drop policy if exists clinic_invites_insert_admin on public.clinic_invites;
create policy clinic_invites_insert_admin on public.clinic_invites
  for insert
  with check (
    public.user_is_clinic_admin(clinic_id)
    and public.clinic_trial_user_cap_available(clinic_id)
  );

drop policy if exists clinic_invites_update_admin on public.clinic_invites;
create policy clinic_invites_update_admin on public.clinic_invites
  for update
  using (public.user_is_clinic_admin(clinic_id))
  with check (public.user_is_clinic_admin(clinic_id));

drop policy if exists clinic_settings_select_member on public.clinic_settings;
create policy clinic_settings_select_member on public.clinic_settings
  for select
  using (public.user_can_access_clinic(clinic_id));

drop policy if exists clinic_settings_update_admin on public.clinic_settings;
create policy clinic_settings_update_admin on public.clinic_settings
  for update
  using (public.user_is_clinic_admin(clinic_id))
  with check (public.user_is_clinic_admin(clinic_id));

drop policy if exists billing_events_select_admin on public.billing_events;
create policy billing_events_select_admin on public.billing_events
  for select
  using (public.user_is_clinic_admin(clinic_id));

drop policy if exists audit_logs_select_admin on public.audit_logs;
create policy audit_logs_select_admin on public.audit_logs
  for select
  using (public.user_is_clinic_admin(clinic_id));

drop policy if exists auth_mfa_factors_select_own on public.auth_mfa_factors;
create policy auth_mfa_factors_select_own on public.auth_mfa_factors
  for select
  using (auth.uid() = user_id);

drop policy if exists auth_mfa_factors_update_own on public.auth_mfa_factors;
create policy auth_mfa_factors_update_own on public.auth_mfa_factors
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

do $$
declare
  scoped_table text;
begin
  foreach scoped_table in array ARRAY[
    'clients',
    'pets',
    'vets',
    'appointments',
    'records',
    'prescriptions',
    'reminders',
    'sales'
  ]
  loop
    execute format('alter table public.%I enable row level security', scoped_table);
    execute format('drop policy if exists %I on public.%I', scoped_table || '_select_member', scoped_table);
    execute format(
      'create policy %I on public.%I for select using (public.user_can_access_clinic(clinic_id))',
      scoped_table || '_select_member',
      scoped_table
    );
    execute format('drop policy if exists %I on public.%I', scoped_table || '_insert_member', scoped_table);
    execute format(
      'create policy %I on public.%I for insert with check (public.user_can_access_clinic(clinic_id))',
      scoped_table || '_insert_member',
      scoped_table
    );
    execute format('drop policy if exists %I on public.%I', scoped_table || '_update_member', scoped_table);
    execute format(
      'create policy %I on public.%I for update using (public.user_can_access_clinic(clinic_id)) with check (public.user_can_access_clinic(clinic_id))',
      scoped_table || '_update_member',
      scoped_table
    );
    execute format('drop policy if exists %I on public.%I', scoped_table || '_delete_member', scoped_table);
    execute format(
      'create policy %I on public.%I for delete using (public.user_can_access_clinic(clinic_id))',
      scoped_table || '_delete_member',
      scoped_table
    );
  end loop;
end
$$;
